In [0]:
#import libraries
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [0]:
#Question 1
data , target = load_digits(n_class = 10 , return_X_y = True)

In [75]:
print(data.shape)
print(target.shape)

(1797, 64)
(1797,)


In [0]:
x = pd.DataFrame(data)
y = pd.DataFrame(target)

In [77]:
x.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [78]:
y.head()

0
0  0
1  1
2  2
3  3
4  4

In [79]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 64 columns):
0     1797 non-null float64
1     1797 non-null float64
2     1797 non-null float64
3     1797 non-null float64
4     1797 non-null float64
5     1797 non-null float64
6     1797 non-null float64
7     1797 non-null float64
8     1797 non-null float64
9     1797 non-null float64
10    1797 non-null float64
11    1797 non-null float64
12    1797 non-null float64
13    1797 non-null float64
14    1797 non-null float64
15    1797 non-null float64
16    1797 non-null float64
17    1797 non-null float64
18    1797 non-null float64
19    1797 non-null float64
20    1797 non-null float64
21    1797 non-null float64
22    1797 non-null float64
23    1797 non-null float64
24    1797 non-null float64
25    1797 non-null float64
26    1797 non-null float64
27    1797 non-null float64
28    1797 non-null float64
29    1797 non-null float64
30    1797 non-null float64
31    1797 non-null float

In [80]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 1 columns):
0    1797 non-null int64
dtypes: int64(1)
memory usage: 14.1 KB


In [0]:
#Question 2
x = pd.DataFrame(StandardScaler().fit_transform(x))

In [82]:
x.head()

0         1         2         3         4         5         6         7   \
0  0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724 -0.125023   
1  0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724 -0.125023   
2  0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724 -0.125023   
3  0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724 -0.125023   
4  0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724 -0.125023   

         8         9     ...           54        55        56        57  \
0 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
1 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
2 -0.059078 -0.624009    ...     0.259230 -0.209785 -0.023596 -0.299081   
3 -0.059078  1.879691    ...     1.072563 -0.209785 -0.023596 -0.299081   
4 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   

         58        59        60        61        62        63  
0  0.086719  0.208293 -0.366771 -1.146647 -0.505670 -0.196008  
1 -1.089383 -0.249010  0.849632  0.548561 -0.505670 -0.196008  
2 -1.089383 -2.078218 -0.164037  1.565686  1.695137 -0.196008  
3  0.282736  0.208293  0.241430  0.379040 -0.505670 -0.196008  
4 -1.089383 -2.306869  0.849632 -0.468564 -0.505670 -0.196008  

[5 rows x 64 columns]

In [113]:
#Question 4
pca = PCA(n_components = 20)
pc = pca.fit_transform(x)
final_x = pd.DataFrame(pc)
final_x.head()

0         1         2         3         4         5         6   \
0  1.914214 -0.954494 -3.946039  2.028704 -0.267128  0.529829 -1.415734   
1  0.588988  0.924655  3.924757 -1.779946 -0.993435 -0.675002  1.878879   
2  1.302047 -0.317169  3.023326 -2.043428 -2.081216  0.934218 -1.296638   
3 -3.020789 -0.868825 -0.801737 -2.186830 -0.556561  0.727483  0.960041   
4  4.528939 -1.093523  0.973141 -1.419368 -1.715141  1.432264  1.074152   

         7         8         9         10        11        12        13  \
0  1.495811  0.124417 -0.821117 -0.499695 -0.789389  0.223291 -0.190893   
1  0.556774  1.081040  0.086422 -0.501255  0.641558 -0.042291 -0.388618   
2  1.155718  0.784019 -1.098546  2.192108 -2.311414 -0.574179 -0.996738   
3 -1.384611  0.258739  0.744686 -1.062653  0.492139 -0.162570  1.001922   
4 -0.967840 -1.660179  1.174174 -1.015433 -1.363987 -0.338164 -0.118998   

         14        15        16        17        18        19  
0  0.849531  0.094293  0.166695 -0.109694  0.417112  0.387987  
1 -0.752516 -0.225518 -0.092813 -0.407714  0.569253 -0.074981  
2 -1.162435  0.408583 -0.268465 -0.480660 -1.062868 -1.153679  
3 -0.154664 -0.971597 -0.902939 -0.357516  1.474128  0.359222  
4  0.723660  0.214358 -0.059325 -0.512573  1.595378  1.140592

In [0]:
#Question 3
train_x , test_x , train_y , test_y = train_test_split(final_x , y , test_size = 0.3 , random_state = 43)

In [115]:
#Question 5
model = LogisticRegression()
model.fit(train_x , train_y)
pred_y = model.predict(test_x)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [116]:
#Question 6
print(accuracy_score(test_y ,pred_y))

0.9351851851851852


In [117]:
print(confusion_matrix(test_y ,pred_y))

[[58  0  0  0  0  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  1  4]
 [ 0  0 43  0  1  0  0  1  0  0]
 [ 0  0  0 38  0  1  0  1  1  0]
 [ 0  1  0  0 54  0  0  1  0  1]
 [ 0  0  0  0  0 54  0  0  0  0]
 [ 0  1  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  1  0  0 54  0  0]
 [ 0  7  0  1  0  2  1  0 53  2]
 [ 0  2  0  1  0  1  0  2  1 56]]


In [118]:
print(classification_report(test_y ,pred_y))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        58
          1       0.77      0.88      0.82        41
          2       1.00      0.96      0.98        45
          3       0.95      0.93      0.94        41
          4       0.96      0.95      0.96        57
          5       0.93      1.00      0.96        54
          6       0.98      0.98      0.98        60
          7       0.92      0.98      0.95        55
          8       0.95      0.80      0.87        66
          9       0.89      0.89      0.89        63

avg / total       0.94      0.94      0.94       540

